// <auto-generated />
namespace StockManagementSW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UserClassUpdatedusernameremoved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserClassUpdatedusernameremoved));
        
        string IMigrationMetadata.Id
        {
            get { return "202011281802425_UserClassUpdatedusernameremoved"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
